aug6/aug6/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from music import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^gaana/',include('music.control')),
    url(r'^login/',views.Login.as_view()),
    url(r'^signup/',views.Register.as_view()),

]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

aug6/music/models.py
from django.db import models
import django.core.urlresolvers

def image_val(value):
    if not(value.name.endswith(".jpg")or value.name.endswith(".png")):
        raise ValueError("Invalid Image")
def song_val(value):
    if not(value.name.endswith(".mp3")or value.name.endswith(".aac")):
        raise ValueError("Invalid File")

class Album(models.Model):
    title=models.CharField(max_length=100)
    artist=models.CharField(max_length=100)
    genre=models.CharField(max_length=50)
    a_logo = models.FileField(validators=[image_val])
    def get_absolute_url(self):
        return reverse('music:song',kwargs={"pk":self.id})


    def __str__(self):
        return "Album: "+self.title+" artist:"+self.artist


class Song(models.Model):
    aid=models.ForeignKey(Album,on_delete=models.CASCADE)
    stitle=models.CharField(max_length=100)
    filetype=models.CharField(max_length=50)
    sartist=models.CharField(max_length=100)
    file=models.FileField(validators=[song_val])
    def __str__(self):
        return "Song: " + self.stitle + " artist:" + self.sartist

    def get_absolute_url(self):
        return reverse('music:song', kwargs={"pk": self.aid.id})

aug6/music/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Album,Song
from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView
from django.contrib.auth import authenticate
from .form import LoginForm,SignUpForm
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate
from django.views.generic.edit import FormView
from django import forms
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

''' view for home in fun
def home(request):
    a=Album.objects.all()
    return render(request,"music/home.html",{'album':a})
    '''
class Home(ListView):
    template_name="music/home.html"
    context_object_name = 'album'
    def get_queryset(self):
       return Album.objects.all()
class Songview(DetailView):
    template_name = "music/song.html"
    model=Album
    context_object_name = "album"

class Login(CreateView):
    from_class = LoginForm
    template_name = "music/login.html"
    def get(self, request, *args, **kwargs):
        myform=LoginForm()
        return render(request,self.template_name,{"form":myform})
    def post(self, request, *args, **kwargs):
        myform = LoginForm(request.POST)
        if myform.is_valid():
            usern=myform.cleaned_data.get("username")
            passw=myform.cleaned_data.get("password")
            val=authenticate(username=usern,password=passw)

            if val is not None:
                request.session["loginuser"]=usern
                #return messages.info(request,"Login Sucessfull Welcome"+usern)
                return redirect("/gaana/")
        return  render(request,"music/login.html",{"form":myform})

def logout(request):
    #v=tkMessageBox.askokcancel("Music World","Do you want to logout")
    #if v==True:
        return redirect("/login/")

class Register(FormView):
    from_class=SignUpForm
    template_name ="music/signup.html"
    def get(self,request,*args,**kwargs):
        myform=SignUpForm()
        return render(request,self.template_name,{"form":myform})
    def post(self,request,*args,**kwargs):
        myform=SignUpForm(request.POST)
        if myform.is_valid():
            usern = myform.cleaned_data.get("username")
            passw1 = myform.cleaned_data.get("password1")
            val = authenticate(username=usern, password=passw1)
            if val is not None:
                        return redirect("/login/")

        return render(request, "music/signup.html", {"form": myform})
class AddAlbum(LoginRequiredMixin,CreateView):
    login_url='/login/'
    redirect_field_name=reverse_lazy("music:album")
    model=Album
    fields = ['title','artist','genre','a_logo']
class AlbumUpdate(UpdateView):
    model=Album
    fields = ['title','artist','genre','a_logo']
class AlbumDelete(DeleteView):
    model=Album
    template_name ='music/Album_delete.html'
    context_object_name = "album"
    success_url = reverse_lazy("music:album")
class AddSong(CreateView):
    model=Song
    template_name ='music/Add_Song.html'
    fields = ['stitle', 'sartist', 'aid','filetype','file']
class Play(DetailView):
    template_name = "music/play.html"
    model=Song
    context_object_name = "song"
class SongDelete(DeleteView):
    model=Song
    template_name ='music/Song_delete.html'
    context_object_name = "song"
    success_url = reverse_lazy("music:album")

aug6/music/templates/music/Add_Song.html
{% extends 'music/master1.html' %}
{% block title %}Add Song{% endblock %}
{% block body %}
    <head xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
   </body>

</head>

</div>
    <form method="post" enctype="multipart/form-data" xmlns="http://www.w3.org/1999/html">
        {% csrf_token %}
    <table width="=321" height="205" align="right" bgcolor="#00ced1" border="5px">
        <td>
         <div align="center"><br \ >
             <div id="login">
      <span class="style2"><font face="Mistral" color="#3300CC" size="28"><u>Add Song </u></font></span><br \></div>
        {% for field in form %}
           <br><br><span class="danger">{{ field.errors }}</span>
            <center><font color="white"><label>{{field.label_tag }}</label></font>
        {{ field }}<br><br>
    {% endfor %}
   <b><strong><font color="black"><input type="submit" value="Add"></font><a href="/gaana/"><font color="black" face="Arial"><input type="button" value="Back">
            </font></a></strong></b></center>

         </div>
    </td>

     </table>
    </div>
  </div>

  <div id="status"></div>
</div>
    </form>
{% endblock %}

aug6/music/templates/music/Album_delete.html
{% extends 'music/master1.html' %}
{% block title %}Delete Album{% endblock %}
{% block body %}
 <div class="col-sm-4 col-md-3">
    <div class="thumbnail">

      <img src="{{ album.a_logo.url }}" width="100px" height="100px">
       <font color="#00008b" face="Viner Hand ITC"><p class="caption">
       <h3>{{ album.title }}</h3>
        <p>{{ album.artist }}<br>{{ album.genre }}</p></font>
          <form method="post" enctype="multipart/form-data" xmlns="http://www.w3.org/1999/html">
        {% csrf_token %}
      <span class="style2"><font face="Mistral" color="#3300CC" size="28"><u>Delete Album </u></font></span><br>
           <b><strong><font color="black"><input type="submit" value="Delete"></font><a href="/gaana/"><font color="black" face="Arial"><input type="button" value="Back">
            </font></a></strong></b></center>
     </form>
    </div>
    </div>
  </div>


</div>
    <div class="col-sm-8 col-md-9">
  <div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">{{ album.title }}</div>
  <table class="table" style="background-color: azure">
    <tr>
        <td><b>Title</b></td>
        <td><b>Artist</b></td>
        <td><b>File</b> </td>
        <td><b>Action</b></td>
    </tr>
    {% for i in album.song_set.all %}
        <tr>
        <td><b><a href="#" class="btn btn-default" role="label"><span class="glyphicon glyphicon-music" aria-hidden="true"></span></a></b>{{ i.stitle }}</td>
        <td>{{ i.sartist }}</td>
        <td>{{ i.filetype }} </td>
        <td>none</td></b>
    </tr>
    {% endfor %}
   </table>
   </div>
</div>
</div>
    </body>
{% endblock %}

aug6/music/templates/music/Album_form.html
{% extends 'music/master1.html' %}
{% block title %}Add Album{% endblock %}
{% block body %}
    <head xmlns="http://www.w3.org/1999/html">
   </body>

</head>

</div>
    <form method="post" enctype="multipart/form-data" xmlns="http://www.w3.org/1999/html">
        {% csrf_token %}
    <table width="=321" height="205" align="right" bgcolor="aqua" border="5px">
        <td>
         <div align="center"><br \ >
             <div id="login">
      <span class="style2"><font face="Mistral" color="#3300CC" size="28"><u>Add Album </u></font></span><br \></div>
        {% for field in form %}
           <br><br><span class="danger">{{ field.errors }}</span>
            <center><font color="white"><label>{{field.label_tag }}</label></font>
        {{ field }}<br><br>
    {% endfor %}
   <b><strong><font color="black"><input type="submit" value="Add"></font><a href="/gaana/"><font color="black" face="Arial"><input type="button" value="Back">
            </font></a></strong></b></center>
         </div>
    </td>

     </table>
    </div>
  </div>

  <div id="status"></div>
</div>
    </form>
{% endblock %}

aug6/music/templates/music/Song_delete.html
{% extends 'music/master1.html' %}
{% block title %}Delete Song{% endblock %}
{% block body %}
 <div class="col-sm-4 col-md-3">
    <div class="thumbnail">

      <img src="{{ album.a_logo.url }}" width="100px" height="100px">
       <font color="#00008b" face="Viner Hand ITC"><p class="caption">
       <h3>{{ song.stitle }}</h3>
        <p>{{ song.sartist }}<br>{{ song.filetype }}</p></font>
          <form method="post" enctype="multipart/form-data" xmlns="http://www.w3.org/1999/html">
        {% csrf_token %}
      <span class="style2"><font face="Mistral" color="#3300CC" size="28"><u>Delete Song </u></font></span><br>
           <b><strong><font color="black"><input type="submit" value="Delete"></font>
               <a href="/gaana/"><font color="black" face="Arial"><input type="button" value="Back">
            </font></a></strong></b></center>
     </form>
    </div>
    </div>
  </div>


</div>
    <div class="col-sm-8 col-md-9">
  <div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">{{ album.title }}</div>
  <table class="table" style="background-color: azure">
    <tr>
        <td><b>Title</b></td>
        <td><b>Artist</b></td>
        <td><b>File</b> </td>
        <td><b>Action</b></td>
    </tr>
    {% for i in album.song_set.all %}
        <tr>
        <td><b><a href="#" class="btn btn-default" role="label"><span class="glyphicon glyphicon-music" aria-hidden="true"></span></a></b>{{ i.stitle }}</td>
        <td>{{ i.sartist }}</td>
        <td>{{ i.filetype }} </td>
        <td>none</td></b>
    </tr>
    {% endfor %}
   </table>
   </div>
</div>
</div>
    </body>
{% endblock %}

aug6/music/templates/music/home.html
{% extends 'music/index.html' %}
{% block add %}

<div class="row">
    {% for i in album %}
  <div class="col-sm-4 col-md-3">
    <div class="thumbnail">
      <a href="{% url 'music:song' i.id %}">
      <img src="{{ i.a_logo.url }}" width="200px" height="200px"></a>
       <font color="#00008b" face="Viner Hand ITC"><p class="caption">
       <h3>{{ i.title }}</h3>
        <p>{{ i.artist }}<br>{{ i.genre }}</p></font>
        <p><a href="{% url 'music:song' i.id %}" class="btn btn-primary" role="button"><span class="glyphicon glyphicon-play" aria-hidden="true">play</span></a>
            <a href="#" class="btn btn-default" role="button"><span class="glyphicon glyphicon-edit" aria-hidden="true">comment</span></a>
             <a href="#" class="btn btn-default" role="button"><span class="glyphicon glyphicon-download-alt" aria-hidden="true">Download</span></a></p>
        <p><a href="{% url 'music:update album' i.id%}" class="btn btn-default" role="button"><span class="glyphicon glyphicon-edit" aria-hidden="true">Update</span></a>
          <a href="#" class="btn btn-default" role="button"><span class="glyphicon glyphicon-thumbs-up" aria-hidden="true">Like</span></a>
          <a href="#" class="btn btn-default" role="button"><span class="glyphicon glyphicon-thumbs-down" aria-hidden="true">Unlike</span></a></p>
          <p> <a href="#" class="btn btn-default" role="button"><span class="glyphicon glyphicon-share" aria-hidden="true">Share</span></a>
          <a href="#" class="btn btn-default" role="button">Buy In<span class="glyphicon glyphicon-usd" aria-hidden="true">.9</span></a>
          <a href="{% url 'music:delete album' i.id %}" class="btn btn-default" role="button">Delete<span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a></p>
      </div>
    </div>
  </div>

    {% endfor %}
    </div>
{% endblock %}

aug6/music/templates/music/index.html
{% extends 'music/master1.html' %}
{% block title %}Albums{% endblock %}
{% block link %}	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="WOW Slider, jQuery Slider Animate, jQuery Slider Text" />
	<meta name="description" content="WOWSlider created with WOW Slider, a free wizard program that helps you easily generate beautiful web slideshow" />
	<!-- Start WOWSlider.com HEAD section -->
	<link rel="stylesheet" type="text/css" href="engine1/style.css" media="screen" />
	<style type="text/css">a#vlb{display:none}</style>
	<script type="text/javascript" src="engine1/jquery.js"></script>
{% endblock %}
	<!-- End WOWSlider.com HEAD section -->
{% block body %}
<div class="jumbotron">
	<!-- Start WOWSlider.com BODY section -->
	<div id="wowslider-container1">
	<div class="ws_images">
<a href="#"><img src="../../static/music/images/data1/images/1.jpg" alt="1" title="1" id="wows0"/></a>
<a href="#"><img src="../../static/music/images/data1/images/p1.jpg" alt="p1" title="p1" id="wows1"/></a>
<a href="#"><img src="../../static/music/images/data1/images/p2.jpg" alt="p2" title="p2" id="wows2"/></a>
<a href="#"><img src="../../static/music/images/data1/images/p3.jpg" alt="p3" title="p3" id="wows3"/></a>
<a href="#"><img src="../../static/music/images/data1/images/p4.jpg" alt="p4" title="p4" id="wows4"/></a>
<a href="#"><img src="../../static/music/images/data1/images/p5.jpg" alt="p5"title="p5" id="wows5"/></a>
<a href="#"><img src="../../static/music/images/data1/images/p6.jpg" alt="p6"title="p6" id="wows6"/></a>
<a href="#"><img src="../../static/music/images/data1/images/p7.jpg" alt="p7"title="p7" id="wows7"/></a>
<a href="#"><img src="../../static/music/images/data1/images/p8.jpg" alt="p8" title="p8" id="wows8"/></a>
<a href="#"><img src="../../static/music/images/data1/images/p9.jpg" alt="p9" title="p9" id="wows9"/></a>
<a href="#"><img src="../../static/music/images/data1/images/p10.jpg"alt="p10" title="p10" id="wows10"/></a>
<a href="#"><img src="../../static/music/images/data1/images/p11.jpg"alt="p11" title="p11" id="wows11"/></a>
<a href="#"><img src="../../static/music/images/data1/images/p12.jpg" alt=p12 title="=p12"id="wows12"/></a>
<a href="#"><img src="../../static/music/images/data1/images/p14.jpg" alt="p14" title="p14" id="wows14"/></a>
<a href="#"><img src="../../static/music/images/data1/images/p15.jpg" alt="p15" title="p15" id="wows15"/></a>
<a href="#"><img src="../../static/music/images/data1/images/p16.jpg" alt="p16" title="p16" id="wows16"/></a>
<a href="#"><img src="../../static/music/images/data1/images/p17.jpg"alt="p17" title="p17" id="wows17"/></a>
</div>
<div class="ws_bullets"><div>
<a href="#wows0" title="1"><img src="../../static/music/images/data1/tooltips/1.jpg" alt="1"/>1</a>
<a href="#wows1" title="p1"><img src="../../static/music/images/data1/tooltips/p1.jpg" alt="p1"/>2</a>
<a href="#wows2" title="p2"><img src="../../static/music/images/data1/tooltips/p2.jpg" alt="p2"/>3</a>
<a href="#wows3" title="p3"><img src="../../static/music/images/data1/tooltips/p3.jpg" alt="p3"/>4</a>
<a href="#wows4" title="p4"><img src="../../static/music/images/data1/tooltips/p4.jpg" alt="p4"/>5</a>
<a href="#wows5" title="p5"><img src="../../static/music/images/data1/tooltips/p5.jpg" alt="p5"/>6</a>
<a href="#wows6" title="p6"><img src="../../static/music/images/data1/tooltips/p6.jpg" alt="p6"/>7</a>
<a href="#wows7" title="p7"><img src="../../static/music/images/data1/tooltips/p7.jpg" alt="p7"/>8</a>
<a href="#wows8" title="p8"><img src="../../static/music/images/data1/tooltips/p8.jpg" alt="p8"/>9</a>
<a href="#wows9" title="p9"><img src="../../static/music/images/data1/tooltips/p9.jpg" alt="p9"/>10</a>
<a href="#wows10" title="p10"><img src="../../static/music/images/data1/tooltips/p10.jpg" alt="p10"/>11</a>
<a href="#wows11" title="p11"><img src="../../static/music/images/data1/tooltips/p11.jpg" alt="p11"/>12</a>
<a href="#wows12" title="p12"><img src="../../static/music/images/data1/tooltips/p12.jpg" alt="p12"/>13</a>
<a href="#wows13" title="p14"><img src="../../static/music/images/data1/tooltips/p14.jpg" alt="p14"/>14</a>
<a href="#wows14" title="p15"><img src="../../static/music/images/data1/tooltips/p15.jpg" alt="p15"/>15</a>
<a href="#wows15" title="p16"><img src="../../static/music/images/data1/tooltips/p16.jpg" alt="p16"/>16</a>
<a href="#wows16" title="p17"><img src="../../static/music/images/data1/tooltips/p17.jpg" alt="p17"/>17</a>
</div></div>
<a style="display:none" href="http://wowslider.com">jQuery Slider Scroll by WOWSlider.com v1.7</a>
	<div class="ws_shadow"></div>
	</div>
	<script type="text/javascript" src="engine1/script.js"></script>
	<!-- End WOWSlider.com BODY section -->

      <h2><font face="Harlow Solid"color="#00ced1">Welcome,Music world!</font></h2>
  <h4><font face="Jokerman"color="blue"><u>Created by Dhurub Saxena</u></font></h4>
  <h5><marquee direction="left"><font face="Magneto" color="black" size="20">“Music is a moral law. It gives soul to the universe, wings to the mind, flight to the imagination, and charm and gaiety to life and to everything.” So Enjoy the music and feel the lyrics with music World!!!</font></marquee></h5>
  <div><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></div> </div></body>
</div>

{% block add %}
{% endblock %}
{% endblock %}

aug6/music/templates/music/login.html
{% extends 'music/master.html' %}
{% block title %}Login{% endblock %}
{% block body %}

   <head>

   </body>

</head>

</div>
    <form method="post" enctype="multipart/form-data" xmlns="http://www.w3.org/1999/html">
        {% csrf_token %}
    <table width="=400" height="450" align="center" bordercolor="red" bgcolor="#20b2aa" border="5px">
    <thead>
<tr >
<td colspan="2" align="center" height="100" width="200">  <span class="style2"><font face="Mistral" color="#3300CC" size="28"><u>Login Here </u></font></span><br \></td>
</tr>
</thead>
        <td>
         <div align="center"><br \ >
             <div id="login">

        {% for field in form %}
           <br><br><span class="danger">{{ field.errors }}</span>
            <center><font color="white"><label>{{field.label_tag }}</label></font>
        {{ field }}<br><br>
    {% endfor %}
   <font color="blue"><input type="submit" value="login"></font> </center><br>
          <tr>
     <td colspan="2" height="50"><div align="center"><font color="yellow">Click</font> <a href="/signup/"><strong>here</strong> </a><font color="yellow">to register now.. </font></div></td>
      </tr>
      </tr>
         </div>
         </div>
    </td>
     </table>
    </div>
  </div>

  <div id="status"></div>
</div>
    </form>
{% endblock %}

aug6/music/templates/music/master.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- Latest compiled and minified bacavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
 <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'music/Logstyle.css' %}">
</head>
<body>
<nav class="navbar navbar-inverse" style="background-color:olivedrab">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#" style="font-family: 'Arial Black'"><font face="Forte"color="#7fff00">GAANA</font></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
      </ul>
      <form class="navbar-form navbar-left"><font face="Forte"color="#191970">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button></font>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#" ><span class="glyphicon glyphicon-plus" aria-hidden="true">Album</span>
</a></li>
          <li><a href="/login/" ><span class="glyphicon glyphicon-user" aria-hidden="true">login</span></a></li>
          <li><a href="/signup/" ><span class="glyphicon glyphicon-registration-mark" aria-hidden="true">Register</span></a></li>
          <li> <a href="#" class="btn btn-default" role="button"><span class="glyphicon glyphicon-envelope" aria-hidden="true">ContactUs</span></a></li>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
{% block body %}
{% endblock %}
</body>
</html>

aug6/music/templates/music/play.html
{% extends 'music/master1.html' %}
{% block title %}Songs{% endblock %}
{% block body %}
<div class="row">
  <div class="col-sm-4 col-md-3">
    <div class="thumbnail" style="background-color: azure">
     <img src="{{ song.aid.a_logo.url }}" width="200px" height="100px">
      <div class="caption">
        <h3><b>{{ song.stitle }}</b></h3>
        <p><b>{{ song.sartist}}<br>{{ song.genre }}</b></p><audio src="{{ song.file.url }}" controls="controls">Your browser does not support this audio element</audio>
      </div>
    </div>
  </div>
</div>
    {% endblock %}

aug6/music/templates/music/signup.html
{% extends 'music/master.html' %}
{% block title %}Registration{% endblock %}
{% block body %}
 <form method="post" enctype="multipart/form-data" xmlns="http://www.w3.org/1999/html">
        {% csrf_token %}
  <table width="=400" height="450" align="center" bordercolor="red" bgcolor="#20b2aa" border="5px">
  <thead>
<tr >
<td colspan="2" align="center" height="100">  <span class="style2"><font face="Mistral" color="#7fff00" size="28"><u>Registration Panel </u></font></span><br \></td>
        <center><div align="center"></div></center><br \ ><br \><br \><br \></tr>
</thead>
  <td>
         <div align="center"><br \ >
             <div id="signup">

        {% for field in form %}
           <br><br><span class="danger">{{ field.errors }}</span>
            <font color="white"><label>{{field.label_tag }}
         </label></font><label>{{ field.help_text }}</label>
        {{ field }}<br><br>
        {% endfor %}
                 <tr>

     <td colspan="2" height="50"><div align="center"><font color="blue"><input type="submit" value="Register"><input type="submit" value="Back"><a href="/login/"></a></font></div></td></div></center>
      <td colspan="2" height="50"><div align="center"><font color="blue"><a href="/login/"></a></font></div></td></div></center>

 </tr>
         </div>
    </td>
     </table>
    </div>
  </div>

  <div id="status"></div>
</div>
 </form>
{% endblock %}

aug6/music/templates/music/song.html
{% extends 'music/master1.html' %}
{% block title %}Songs{% endblock %}
{% block body %}
<div class="row">
  <div class="col-sm-4 col-md-3">
    <div class="thumbnail" style="background-color: azure">
     <img src="{{ album.a_logo.url }}" width="200px" height="100px">
      <div class="caption">
        <h3><b>{{ album.title }}</b></h3>
        <p><b>{{ album.artist }}<br>{{ album.genre }}</b></p>
      </div>
    </div>
  </div>
<div class="col-sm-8 col-md-9">
  <div class="panel panel-primary">
  <!-- Default panel contents -->
  <div class="panel-heading">{{ album.title }}</div>
  <table class="table" style="background-color: azure">
    <tr>
        <td><b>Title</b></td>
        <td><b>Artist</b></td>
        <td><b>File</b> </td>
        <td><b>Action</b></td>
        <td><b>Action</b></td>
        <td><b>Delete</b></td>
    </tr>
    {% for i in album.song_set.all %}
        <tr>
        <td><b><a href="#" class="btn btn-default" role="label"><span class="glyphicon glyphicon-music" aria-hidden="true"></span></a></b>{{ i.stitle }}</td>
        <td>{{ i.sartist }}</td>
        <td>{{ i.filetype }} </td>
        <td><b><a href='{% url 'music:play' i.id  %}' class="btn btn-primary" role="button"><span class="glyphicon glyphicon-music" aria-hidden="true">Play</span></a></b></td>
        <td><b><a href='#' class="btn btn-danger" role="button"><span class="glyphicon glyphicon-stop" aria-hidden="true">Stop</span></a></b></td>
        <td><b><a href='{% url 'music:delete song' i.id %}' class="btn btn-danger" role="button"><span class="glyphicon glyphicon-trash" aria-hidden="true">Delete</span></a></b></td>
    </tr>
    {% endfor %}
   </table>
   </div>
</div>
</div>
{% endblock %}